### ISSUE TITLE
Add id to ItemInputDTO

### ISSUE THREAD

**Issue by GR0ZA** [lab-64/split-the-bill-server#113]
We need this i. e. for PUT /bill -> right now all items are replaced instead of updated.

Would be nice if we can keep one DTO for input. In this case "id" on i. e. POST /item should simply be ignored.
Verify whether splitting in more DTOs is a better idea.

**Comment by f-odc** [comment]
I would stall this issue a little bit because maybe this functionality will not be used in the future. We already have an endpoint to update items, maybe this will be sufficient.

The related branch contains some possible adjustments.

**Comment by GR0ZA** [comment]
@f-odc Yes I think it's reasonable to delete this possibility since it's not working 100% properly anyway.

**Comment by f-odc** [comment]
I decided to permit updating items, ownerID and groupID when updating the bill. It is now only possible to update the name, the date and the stored information which user has seen the bill already.
