### ISSUE TITLE
Add Profile Picture

### ISSUE THREAD

**Issue by f-odc** [lab-64/split-the-bill-server#122]
Add profile picture to a user.

**Comment by f-odc** [comment]
@GR0ZA In which form do you need the images to be in the frontend?

**Comment by GR0ZA** [comment]
I think every common image format like .jpg or .png is fine. It probably also make sense to set some max MB size 😀

**Comment by f-odc** [comment]
@GR0ZA If you have time you could check the image upload endpoint if the used format is reasonable for frontend usage.

**Comment by f-odc** [comment]
Some open questions:
1. Which file types should we allow?
2. How big can uploaded images be?
3. Do we resize the images?
4. How to check for malware in images?
