### ISSUE TITLE
Update items on PUT /bill

### ISSUE THREAD

**Issue by GR0ZA** [lab-64/split-the-bill-server#156]
Usecase: we want to add/delete/update all items of a bill at once (see workflow in frontend) instead of doing that with several API requests.

**Comment by f-odc** [comment]
We could use a single endpoint for updating the bill and let the backend handle the updating of the related bill items by looping through all items. This would require only small code changes but we would loose the atomic update of the whole bill. If an item cannot be updated, the whole bill gets updated nevertheless.
