### ISSUE TITLE
Add Group Invitations in Database

### ISSUE THREAD

**Issue by f-odc** [lab-64/split-the-bill-server#38]
Includes #29

**Comment by f-odc** [comment]
TODO: delete userservice and userstorage from group handler and group service if group invitation will be moved.

**Comment by GR0ZA** [comment]
TODOs: 
- [ ] Fix Ephemeral
- [ ] Add Groups conversion in `entity.user`

**Comment by f-odc** [comment]
We changed the way invitation is handled. The group creation request is no longer responsible to create invitations. We added an own request for this functionality (/api/invitation). Now we create groups and invitations separately.
The client will be responsible to perform both requests when a new group with invitees is created.

**Comment by f-odc** [comment]
> TODOs:
> 
> * [ ]  Fix Ephemeral
> * [x]  Add Groups conversion in `entity.user`

For the ephemeral fix a new issue is created. It would go beyond the scope of this issue to handle it here.
