### ISSUE TITLE
Implement an authorization mechanism

### ISSUE THREAD

**Issue by GR0ZA** [lab-64/split-the-bill-server#48]
Thoroughly explore different authorization methods to figure out the best way to control access securely in our app.

**Comment by f-odc** [comment]
We have the following endpoints:

Authorized requests are market with a *
- symbolize additional authorization

Bill
*Get All Bills by User ID - requesterID == userID
*Create Bill
*Add Item to Bill - requester == bill.Owner
*Get Item by ID - requester in group.Members
*Change Item - requester == bill.Owner
*Get Bill By ID - requester in group.Members
*Update Bill - requester == bill.Owner

Group
*Get Groups by User
*Create Group
*Get Group by ID - requester in group.Members
*Update Group - requester == group.Owner

Invitation
Get Group Invitation By ID
*Accept Group Invitation

User
Get all Users
Register User
Login User
(can be deleted) Get detailed User data by ID 
*Update User requester == updated user
*Delete User requester == user

**Comment by f-odc** [comment]
@GR0ZA it would be helpful if you can look over the above provided enumeration and add some missing authorization/authentication.
