### ISSUE TITLE
Add DB Bill Creation

### ISSUE THREAD

**Issue by f-odc** [lab-64/split-the-bill-server#56]
Including:

- [x] Create Bill
- [x] Create Item
- [x] Add Item To Bill

**Comment by f-odc** [comment]
TODO: 
Decide on which struct (bill or group) should have a full reference to each other. We have a many to many relation so one struct will store a reference to the other struct and the other one stores only the UUID.

**Comment by GR0ZA** [comment]
Recently I‘ve been thinking about the modelling in our app and I reckon it'd be wise for us to chat before diving into the implementation :) Just a short heads-up:

- bills and groups don't strike me as a many-to-many. Feels more like a belongs-to/has-many setup (one bill belongs to a group, but a group can have many bills).
- bills and users is many-to-many indeed (contributors)
- the GroupDTO should probably pack the BillDTO, not the other way around
- adding bills without items should be possible
- we need to discuss on how to roll out the "bill-splitting" (who pays how much - picking per item is an option, but not the only one, like 50/50 and such)

As you see it‘s a lot to consider 😄
