### ISSUE TITLE
Add Bill Creation

### ISSUE THREAD

**Issue by f-odc** [lab-64/split-the-bill-server#7]
Implement Bill Creation.

Sub Tasks:

- [x] Add Groups
- [x] Add Invitations
- [x] Add Items
- [x] Add Bills

Relationships:

User
- PendingGroupInvitations
- Groups

Groups
- MemberUIDs
- Bills

**Comment by f-odc** [comment]
@GR0ZA are the relationships reasonable? we could implement bills with the relationship to groups but i think that is worst. with these relationships we can query the logged in user and see all groups with the corresponding bills.

**Comment by GR0ZA** [comment]
@f-odc What's the work left here? Would be nice to merge the changes in dev
